# Setup
title:               Bekbolot
tagline:             'You shall read'
description:         'A little cave in the internet desert'
url:                 http://khudabek.github.io
baseurl:             '/'
root:                '/'
paginate:            5
permalink:           pretty
remote_theme:        poole/lanyon
encoding:            UTF-8

# About/contact
author:
  name:              Bekbolot Khudaiberidev
  url:               https://twitter.com/alpkarakush
  email:             bekbolot.kudayberdiev@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-compose
  - font-awesome-sass
  - travis
  - jekyll-mentions
  - github-pages

google_analytics_id: #UA-XXXX-Y

